---
- name: Apply app manifests
  kubernetes.core.k8s:
    state: present
    src: "{{ item }}"
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  loop:
    - "{{ playbook_dir }}/../manifests/configmap.yaml"
    - "{{ playbook_dir }}/../manifests/deployments.yaml"
    - "{{ playbook_dir }}/../manifests/services.yaml"
    - "{{ playbook_dir }}/../manifests/ingress.yaml"
